#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2006-2010 (ita)

# the following two variables are used by the target "waf dist"
VERSION='0.0.1'
APPNAME='cc_test'

top = '.'

#Configure.autoconfig = True

def options(opt):
	opt.load('compiler_c')
	opt.load('gnu_dirs')
	opt.load('python')

def configure(conf):
	conf.load('compiler_c')
	conf.load('python')
	conf.check_python_version((2,4,2))
	conf.check_python_headers()
	#conf.check_cc(fragment="int main() { return 0; }\n")

	conf.check_cc(lib='m', uselib_store='M', mandatory=False)
	conf.check_cc(lib='ssl', uselib_store='SSL', mandatory=False)
	conf.check_cc(framework_name='Accelerate', uselib_store='ACCELERATE', mandatory=False)
	conf.check_cc(framework_name='CoreAudio', uselib_store='CORE_AUDIO', mandatory=False)
	conf.write_config_header('config.h')

    # exclude system libraries, force a particular folder (see strictlib below)
    #conf.check(features='c cprogram strictlib', lib = 'gif', libpath = ['/opt/lib'])

def build(bld):
	bld(features="c cprogram ordered_linker", source="main.c", target="hello", use="M ACCELERATE")
	bld(features="c cprogram ordered_linker", source="main.c", target="hello2", use="ACCELERATE M")
	bld(features="c cshlib ordered_linker", source="hello.c", target="hello", use="ACCELERATE M")
	bld(features="c cshlib ordered_linker", source="hello.c", target="hello2", use="ACCELERATE M CORE_AUDIO SSL")

	# then a c extension module
	bld(features='c cshlib pyext ordered_linker', source='spammodule.c', target='spam', use="ACCELERATE M CORE_AUDIO SSL")
